name: imgreat_phone_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # notifications:
  #   git:
  #     url: git://github.com/cph-cachet/flutter-plugins.git
  #     path: packages/notifications
  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.1.4
  firebase_storage: ^3.1.1
  firebase_messaging: ^6.0.12
  fluttertoast: ^3.1.3
  intl: ^0.16.1
  flutter_local_notifications: ^1.2.0+3

  sqflite: any
  path_provider: any
  shared_preferences: ^0.5.2
  share: ^0.6.1+1
  speech_recognition: ^0.3.0+1
  
  swipedetector: ^1.2.0
  image_picker: 
  cached_network_image:
  photo_view:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/ic_launcher.png"
  image_path_ios: "assets/icons/ic_launcher.png"

flutter:
  uses-material-design: true

  assets: 
    - assets/images/logo.png
    - assets/images/fitness.jpg
    - assets/icons/ic_launcher.png
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif
  

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
    - family: Microsoft-JhengHei
      fonts:
        - asset: assets/fonts/Microsoft-JhengHei.ttf
